baseurl: /casparcg-template-marketplace

collections:
  caspar_templates:
    output: true
    permalink: /templates/:name

defaults:
  -
    scope:
      path: ""
      type: "caspar_templates"
    values:
      layout: "template"